apiVersion: 1

# list of datasources to insert/update
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db.:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: 'postgres'
    jsonData:
      sslmode: 'disable'